In [1]:
import numpy as np
import tensorflow as tf

In [11]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0],[1],[1],[0]])

In [30]:
tf.set_random_seed(1234)
in_dim=2
in_dim2=3
x=tf.placeholder(tf.float32,shape=[None,in_dim]) #1헹2열
t=tf.placeholder(tf.float32,shape=[None,1])

#입력층-은닉층
W=tf.Variable(tf.truncated_normal([in_dim,in_dim2],seed=0)) #2행. 행렬곱에 의해 x의 열의 갯수와 같아야함.(in_dim)
b=tf.Variable(tf.zeros([in_dim2]))
h=tf.nn.sigmoid(tf.matmul(x,W)+b)

#은닉층-출력층
V=tf.Variable(tf.truncated_normal([in_dim2,1],seed=23)) #W의 열의 갯수,b의 차원, V의 행의 갯수가 같아야함.(in_dim2)
c=tf.Variable(tf.zeros([1]))
y=tf.nn.sigmoid(tf.matmul(h,V)+c)

cross_entropy=-tf.reduce_mean(t*tf.log(y)+(1-t)*tf.log(1-y))

lr=0.1
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

correct_prediction = tf.equal(tf.to_float(tf.greater(y,0.5)),t)

In [31]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print("W=\n",sess.run(W))
print("V=",sess.run(V))

W=
 [[-0.30200204  1.99549484 -1.43466127]
 [ 0.05055132 -0.51051253  0.85555148]]
V= [[-1.31181252]
 [ 0.15874536]
 [ 0.09491279]]


In [32]:
for epoch in range(8000):
    sess.run(train_step, feed_dict={
        x:X,
        t:Y
    })
    if epoch%1000==0:
        print('epoch:',epoch)

epoch: 0
epoch: 1000
epoch: 2000
epoch: 3000
epoch: 4000
epoch: 5000
epoch: 6000
epoch: 7000


In [33]:
classified=correct_prediction.eval(session=sess,feed_dict={
    x:X,
    t:Y
})
prob=y.eval(session=sess, feed_dict={
    x:X
})

print('classified: ', classified)
print()
print('output probability: ', prob)

classified:  [[ True]
 [ True]
 [ True]
 [ True]]

output probability:  [[ 0.01637425]
 [ 0.98344707]
 [ 0.98384976]
 [ 0.0132083 ]]


In [34]:
sess.close()

In [35]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [36]:
iris=load_iris()

x=iris.data
y=iris.target
target_names=iris.target_names
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=10,test_size=0.25)
print(X_train.shape)
print(y_train.shape)

(112, 4)
(112,)


In [38]:
count_train=np.bincount(y_train)
print(count_train)

[39 35 38]


In [42]:
Y_train=np.eye(3)[y_train].astype(int) #3x3 identity matrix 의 y_train -1 번째 row
Y_test=np.eye(3)[y_test].astype(int)
print(X_train.shape,Y_train.shape)

(112, 4) (112, 3)


In [45]:
in_dim=4
out_dim=3

In [41]:
tf.argmax?

In [54]:
#model
hidden_dim=10

tf.set_random_seed(1234)
x=tf.placeholder(tf.float32, shape=[None,in_dim])
t=tf.placeholder(tf.float32, shape=[None,out_dim])

#입력층-은닉층
W=tf.Variable(tf.truncated_normal([in_dim,hidden_dim],seed=0))
b=tf.Variable(tf.zeros([hidden_dim]))
h=tf.nn.sigmoid(tf.matmul(x,W)+b)

#은닉층-입력층
V=tf.Variable(tf.truncated_normal([hidden_dim,out_dim],seed=23))
c=tf.Variable(tf.zeros([out_dim]))
y=tf.nn.softmax(tf.matmul(h,V)+c) #softmax : multiclass

cross_entropy=-tf.reduce_mean(tf.reduce_sum(t*tf.log(y),reduction_indices=[1]))

lr=0.05
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

correct_prediction=tf.equal(tf.argmax(y,1),tf.argmax(t,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [48]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [52]:
loss_train=cross_entropy.eval(session=sess, feed_dict={
    x:X_train,
    t:Y_train
})
accuracy_train=accuracy.eval(session=sess, feed_dict={
    x:X_train,
    t:Y_train
})

print("train_set loss =", loss_train, "\ntrain_set accuracy =", accuracy_train)

train_set loss = 1.63547 
train_set accuracy = 0.348214


In [53]:
n_epoch =1000