In [1]:
import numpy as np
import tensorflow as tf

C:\Users\JinGyu Choi\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0],[1],[1],[0]])

In [3]:
tf.set_random_seed(123)
x=tf.placeholder(dtype=tf.float32,shape=[None,2])
t=tf.placeholder(tf.float32,shape=[None,1])

#입력층-은닉층
W=tf.Variable(tf.truncated_normal([2,2],seed=0))
b=tf.Variable(tf.zeros([2]))
h=tf.nn.sigmoid(tf.matmul(x,W)+b)

#은닉층-출력층
V=tf.Variable(tf.truncated_normal([2,1],seed=12))
c=tf.Variable(tf.zeros([1]))
y=tf.nn.sigmoid(tf.matmul(h,V)+c)

cross_entropy=-tf.reduce_mean(t*tf.log(y)+(1-t)*tf.log(1-y))

lr=0.1
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

correct_prediction=tf.equal(tf.to_float(tf.greater(y,0.5)),t)

In [4]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print('W = ',sess.run(W))
print('V = ',sess.run(V))

W =  [[-0.05961856  1.6006662 ]
 [-1.3575578  -0.305309  ]]
V =  [[0.9301948 ]
 [0.09106961]]


In [5]:
for epoch in range(8000):
    sess.run(train_step,feed_dict={
        x:X,
        t:Y
    })
    if epoch%1000==0:
        print('epoch = ',epoch)

epoch =  0
epoch =  1000
epoch =  2000
epoch =  3000
epoch =  4000
epoch =  5000
epoch =  6000
epoch =  7000


In [6]:
classified=correct_prediction.eval(session=sess,feed_dict={x:X,t:Y})
prob=y.eval(session=sess,feed_dict={x:X})
print('classified=',classified)
print()
print('output = ',prob)

classified= [[ True]
 [ True]
 [ True]
 [ True]]

output =  [[0.01836585]
 [0.97548896]
 [0.9834351 ]
 [0.01541846]]


In [7]:
sess.close()

In [8]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [10]:
iris.target?

In [14]:
iris=load_iris()
x=iris.data
y=iris.target
target_names=iris.target_names
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=21,test_size=0.25)
print(X_train.shape)
print(y_train.shape)
print(y_train)

(112, 4)
(112,)
[0 2 2 2 2 1 2 0 0 0 1 0 1 0 1 2 1 1 0 0 2 0 0 0 0 0 1 1 0 2 1 0 0 2 1 0 2
 1 2 0 2 0 0 1 2 1 1 0 2 1 0 2 1 1 2 1 2 1 2 2 0 0 2 2 0 1 2 1 1 2 1 2 0 2
 2 0 0 1 2 0 0 1 2 0 0 1 2 2 0 2 1 0 1 2 1 0 2 2 1 1 2 2 2 1 2 1 1 2 2 0 0
 1]


In [15]:
#change formation for output
count_train=np.bincount(y_train)
print(count_train)

[37 35 40]


In [23]:
Y_train=np.eye(3)[y_train].astype(int)
Y_test=np.eye(3)[y_test].astype(int)

print(X_train.shape,Y_train.shape)
print(X_train,Y_train)

(112, 4) (112, 3)
[[4.4 3.  1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.9 3.  5.1 1.8]
 [6.3 3.4 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [6.2 2.9 4.3 1.3]
 [6.9 3.1 5.1 2.3]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.3 3.  1.1 0.1]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [5.  3.3 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [7.7 2.6 6.9 2.3]
 [5.7 2.8 4.5 1.3]
 [5.8 2.7 4.1 1. ]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [7.7 3.  6.1 2.3]
 [4.7 3.2 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [5.7 2.9 4.2 1.3]
 [5.5 2.5 4.  1.3]
 [5.2 3.5 1.5 0.2]
 [6.7 2.5 5.8 1.8]
 [6.4 3.2 4.5 1.5]
 [4.9 3.  1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [4.9 2.5 4.5 1.7]
 [6.7 3.1 4.7 1.5]
 [4.9 3.1 1.5 0.1]
 [6.5 3.  5.8 2.2]
 [5.  2.3 3.3 1. ]
 [6.1 2.6 5.6 1.4]
 [5.  3.5 1.6 0.6]
 [6.4 2.7 5.3 1.9]
 [5.1 3.4 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [6.5 3.  5.5 1.8]
 [5.6 2.9 3.6 1.3]
 [5.6 2.7 4.2 1.3]
 [4.8 3.4 1.9 0.2]
 [6.4 2.8 5.6 2.2]
 [6.6 2.9 4.6 1.3]
 [4.4 2.9 1.4 0.2]
 [6.1 3.  4.9

In [21]:
p=np.eye(3)[2]
print(p)

[0. 0. 1.]


In [24]:
in_dim=4
out_dim=3

In [25]:
tf.argmax?

In [32]:
#modelling
hidden_dim=10

tf.set_random_seed(1234)

x=tf.placeholder(tf.float32, shape=[None,in_dim])
t=tf.placeholder(tf.float32, shape=[None,out_dim])

#input-hidden
W=tf.Variable(tf.truncated_normal([in_dim,hidden_dim],seed=0))
b=tf.Variable(tf.zeros([hidden_dim]))
h=tf.nn.sigmoid(tf.matmul(x,W)+b)

#hidden-output
V=tf.Variable(tf.truncated_normal([hidden_dim,out_dim],seed=3))
c=tf.Variable(tf.zeros([out_dim]))
y=tf.nn.softmax(tf.matmul(h,V)+c)

cross_entropy=-tf.reduce_mean(tf.reduce_sum(t*tf.log(y)+(1-t),reduction_indices=[1]))

lr=0.05
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

correct_prediction=tf.equal(tf.argmax(y,1),tf.argmax(t,1))
accuracy=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))

In [33]:
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [34]:
loss_train=cross_entropy.eval(session=sess,feed_dict={x:X_train,t:Y_train})
accuracy_train=accuracy.eval(session=sess, feed_dict={x:X_train,t:Y_train})
print("train_set loss = ",loss_train)
print("\ntrain_set accuracy = ",accuracy_train)

train_set loss =  0.7786819

train_set accuracy =  0.33035713


In [35]:
n_epoch=2000
for epoch in range(n_epoch):
    sess.run(train_step, feed_dict={
        x:X_train,
        t:Y_train
    })
    if epoch%100==0:
        loss_train=cross_entropy.eval(session=sess,feed_dict={x:X_train,t:Y_train}) #윗줄과 동일
        accuracy_train=accuracy.eval(session=sess,feed_dict={x:X_train,t:Y_train})
        print('epoch = ',epoch,
             '\nloss_train = ',loss_train,
             '\ntrain_set accuracy = ',accuracy_train)

epoch =  0 
loss_train =  0.63769025 
train_set accuracy =  0.33035713
epoch =  100 
loss_train =  -0.943544 
train_set accuracy =  0.6875
epoch =  200 
loss_train =  -1.1785754 
train_set accuracy =  0.6875
epoch =  300 
loss_train =  -1.3240498 
train_set accuracy =  0.6964286
epoch =  400 
loss_train =  -1.4057119 
train_set accuracy =  0.72321427
epoch =  500 
loss_train =  -1.4566381 
train_set accuracy =  0.76785713
epoch =  600 
loss_train =  -1.4956139 
train_set accuracy =  0.8660714
epoch =  700 
loss_train =  -1.5308654 
train_set accuracy =  0.91071427
epoch =  800 
loss_train =  -1.5654174 
train_set accuracy =  0.9375
epoch =  900 
loss_train =  -1.5998609 
train_set accuracy =  0.97321427
epoch =  1000 
loss_train =  -1.6336672 
train_set accuracy =  0.97321427
epoch =  1100 
loss_train =  -1.6659406 
train_set accuracy =  0.98214287
epoch =  1200 
loss_train =  -1.6958827 
train_set accuracy =  0.98214287
epoch =  1300 
loss_train =  -1.723006 
train_set accuracy =  0.9

In [39]:
loss_train=cross_entropy.eval(session=sess,feed_dict={x:X_train,t:Y_train})
accuracy_train=accuracy.eval(session=sess,feed_dict={x:X_train,t:Y_train})
print("train_set loss = ",loss_train,
     "\ntrain_set accuracy = ",accuracy_train)

y_val_train=y.eval(session=sess,feed_dict={x:X_train, t:Y_train})
print(y_val_train)
print(y_val_train.shape)

classified=correct_prediction.eval(session=sess,feed_dict={x:X_train,t:Y_train})
print(classified)

train_set loss =  -1.8407856 
train_set accuracy =  0.98214287
[[0.9486301  0.04749752 0.00387238]
 [0.00433012 0.10181546 0.8938544 ]
 [0.00815184 0.18500336 0.8068448 ]
 [0.00383698 0.09229118 0.9038719 ]
 [0.0035499  0.083618   0.9128321 ]
 [0.05277846 0.86746967 0.07975185]
 [0.01550227 0.33710074 0.647397  ]
 [0.95556563 0.04099947 0.00343493]
 [0.9494614  0.04671062 0.00382801]
 [0.95366967 0.04280564 0.0035247 ]
 [0.02243227 0.45525897 0.52230877]
 [0.94886607 0.04725258 0.0038814 ]
 [0.04658701 0.8397463  0.11366662]
 [0.9521646  0.04417742 0.00365801]
 [0.05522171 0.886368   0.05841025]
 [0.00236331 0.05878178 0.93885493]
 [0.03700152 0.6944829  0.26851556]
 [0.05689722 0.8692112  0.07389154]
 [0.94578344 0.05014393 0.00407258]
 [0.9527938  0.04358181 0.00362438]
 [0.00430737 0.10376514 0.8919274 ]
 [0.94518614 0.05069492 0.00411889]
 [0.95446783 0.04201673 0.00351537]
 [0.95665115 0.03999493 0.00335394]
 [0.9520014  0.04433777 0.00366083]
 [0.9496544  0.04650656 0.00383901]
 

In [40]:
loss_test=cross_entropy.eval(session=sess,feed_dict={x:X_test,t:Y_test})
accuracy_test=accuracy.eval(session=sess,feed_dict={x:X_test,t:Y_test})

print("test_set loss = ",loss_test,
     "\ntest_set accuracy = ",accuracy_test)

y_val_test=y.eval(session=sess,feed_dict={x:X_test,t:Y_test})
print(y_val_test)

classified=correct_prediction.eval(session=sess, feed_dict={x:X_test,t:Y_test})
print(classified)

test_set loss =  -1.7793278 
test_set accuracy =  0.94736844
[[0.05339548 0.8567043  0.08990011]
 [0.9448412  0.05098684 0.004172  ]
 [0.95145226 0.04483794 0.00370977]
 [0.95180285 0.04449841 0.00369867]
 [0.05417123 0.8608123  0.08501647]
 [0.05350315 0.8794616  0.06703518]
 [0.9491136  0.04701343 0.00387291]
 [0.00488753 0.11347802 0.8816344 ]
 [0.94533706 0.05053505 0.00412799]
 [0.95361686 0.04280814 0.00357498]
 [0.06017474 0.8665975  0.07322775]
 [0.0536177  0.8562773  0.09010497]
 [0.00349965 0.08508699 0.9114133 ]
 [0.00469032 0.11314116 0.8821686 ]
 [0.9360347  0.05921851 0.00474676]
 [0.03224733 0.6410529  0.3266998 ]
 [0.01921278 0.404438   0.57634926]
 [0.04085728 0.75508714 0.20405559]
 [0.957352   0.03932554 0.00332254]
 [0.00433012 0.10181546 0.8938544 ]
 [0.01356032 0.294992   0.6914477 ]
 [0.05314928 0.8537911  0.09305952]
 [0.0080476  0.18221287 0.8097395 ]
 [0.05430407 0.87761855 0.06807731]
 [0.9510103  0.04526833 0.00372139]
 [0.05156834 0.8003682  0.1480635 ]
 [0

In [41]:
sess.close()